// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, avatar_url, phone, google_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, avatar_url, phone, google_id, created_at, updated_at
`

type CreateUserParams struct {
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Phone     pgtype.Text `json:"phone"`
	GoogleID  string      `json:"google_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Phone,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Phone,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, name, avatar_url, phone, google_id, created_at, updated_at
FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Phone,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPhoneByGoogleID = `-- name: UpdateUserPhoneByGoogleID :exec
UPDATE users
SET phone = $2,
    updated_at = now()
WHERE google_id = $1
  AND $2::text <> ''
`

type UpdateUserPhoneByGoogleIDParams struct {
	GoogleID string      `json:"google_id"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateUserPhoneByGoogleID(ctx context.Context, arg UpdateUserPhoneByGoogleIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPhoneByGoogleID, arg.GoogleID, arg.Phone)
	return err
}
