version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - gocritic

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-naming
      - name: error-return
      - name: exported
        arguments:
          - checkPrivateReceivers: false
      - name: indent-error-flow

issues:
  exclude-dirs:
    - pkg/db

formatters:
  enable:
    - gofmt
    - goimports
